export const marketAbi = [
  { type: 'constructor', inputs: [], stateMutability: 'nonpayable' },
  {
    type: 'function',
    name: 'cancelOrder',
    inputs: [{ name: 'orderId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'emergencyRecover',
    inputs: [
      { name: 'token', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'to', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'fillOrder',
    inputs: [
      { name: 'orderId', type: 'uint256', internalType: 'uint256' },
      { name: 'amountToBuy', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getOrder',
    inputs: [{ name: 'orderId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct P2PMarket.Order',
        components: [
          { name: 'orderId', type: 'uint256', internalType: 'uint256' },
          { name: 'seller', type: 'address', internalType: 'address' },
          { name: 'tokenToSell', type: 'address', internalType: 'address' },
          { name: 'tokenToPay', type: 'address', internalType: 'address' },
          { name: 'amountToSell', type: 'uint256', internalType: 'uint256' },
          { name: 'amountRemaining', type: 'uint256', internalType: 'uint256' },
          { name: 'pricePerToken', type: 'uint256', internalType: 'uint256' },
          { name: 'minOrderSize', type: 'uint256', internalType: 'uint256' },
          { name: 'isActive', type: 'bool', internalType: 'bool' },
          { name: 'createdAt', type: 'uint256', internalType: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getTotalOrders',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'orders',
    inputs: [{ name: 'id', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'orderId', type: 'uint256', internalType: 'uint256' },
      { name: 'seller', type: 'address', internalType: 'address' },
      { name: 'tokenToSell', type: 'address', internalType: 'address' },
      { name: 'tokenToPay', type: 'address', internalType: 'address' },
      { name: 'amountToSell', type: 'uint256', internalType: 'uint256' },
      { name: 'amountRemaining', type: 'uint256', internalType: 'uint256' },
      { name: 'pricePerToken', type: 'uint256', internalType: 'uint256' },
      { name: 'minOrderSize', type: 'uint256', internalType: 'uint256' },
      { name: 'isActive', type: 'bool', internalType: 'bool' },
      { name: 'createdAt', type: 'uint256', internalType: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'placeOrder',
    inputs: [
      { name: 'tokenToSell', type: 'address', internalType: 'address' },
      { name: 'tokenToPay', type: 'address', internalType: 'address' },
      { name: 'amountToSell', type: 'uint256', internalType: 'uint256' },
      { name: 'pricePerToken', type: 'uint256', internalType: 'uint256' },
      { name: 'minOrderSize', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateOrder',
    inputs: [
      { name: 'orderId', type: 'uint256', internalType: 'uint256' },
      { name: 'newPrice', type: 'uint256', internalType: 'uint256' },
      { name: 'newMinOrderSize', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'OrderCancelled',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'seller',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OrderFilled',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'buyer',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'amountFilled',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'paymentAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OrderPlaced',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'seller',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'tokenToSell',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'tokenToPay',
        type: 'address',
        indexed: false,
        internalType: 'address',
      },
      {
        name: 'amountToSell',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'pricePerToken',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'minOrderSize',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OrderUpdated',
    inputs: [
      {
        name: 'orderId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'newPrice',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'newMinOrderSize',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
  },
  { type: 'error', name: 'ReentrancyGuardReentrantCall', inputs: [] },
];
